---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/Anki1233/concourse-basic.git

- name: git-resource-image
  type: docker-image
  source:
    repository: ((docker-username))/resource-tutorial-1
    username: ((docker-username))
    password: ((docker-password))


jobs:
- name: build-docker-file
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - put: git-resource-image
    params: 
      build: resource-tutorial
